#!/usr/bin/env python3
"""
Reference simulation for a phase-first Hamiltonian generated by an
Information/Intention Operator, Collatz rhythm, and twin-prime seeds.

This script is intentionally small and dependency-light. It does not claim a
physical validation; it tests algebraic consistency of the proposed formalism:
phase accumulation, Euler-Berry closure error epsilon, and dependence on the
D-sector/topological defect index.
"""
from __future__ import annotations

import argparse
import json
import math
from pathlib import Path
from typing import Iterable, List, Tuple

import matplotlib.pyplot as plt
import numpy as np

KAPPA = math.log(2.0) / (24.0 * math.pi)


def is_prime(n: int) -> bool:
    if n < 2:
        return False
    if n in (2, 3):
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    r = int(math.isqrt(n))
    f = 5
    while f <= r:
        if n % f == 0 or n % (f + 2) == 0:
            return False
        f += 6
    return True


def twin_primes(limit: int) -> List[Tuple[int, int]]:
    return [(p, p + 2) for p in range(3, limit + 1) if is_prime(p) and is_prime(p + 2)]


def collatz_step(n: int) -> int:
    if n <= 0:
        raise ValueError("Collatz seed must be positive")
    return n // 2 if n % 2 == 0 else 3 * n + 1


def collatz_orbit(n: int, steps: int) -> List[int]:
    orbit = [n]
    for _ in range(steps):
        n = collatz_step(n)
        orbit.append(n)
    return orbit


def pair_orbit(seed: Tuple[int, int], steps: int) -> Tuple[List[int], List[int]]:
    return collatz_orbit(seed[0], steps), collatz_orbit(seed[1], steps)


def collatz_log_rhythm(a: Iterable[int], b: Iterable[int], alpha: float = 0.35) -> np.ndarray:
    """A bounded Collatz rhythm from average log contraction/expansion.

    rho_k = 1 + alpha * tanh(mean(log(n_{k+1}/n_k))).
    It is only a test rhythm; the formal paper leaves this choice modular.
    """
    arr_a = np.array(list(a), dtype=float)
    arr_b = np.array(list(b), dtype=float)
    ratios_a = np.log(arr_a[1:] / arr_a[:-1])
    ratios_b = np.log(arr_b[1:] / arr_b[:-1])
    rhythm = 1.0 + alpha * np.tanh(0.5 * (ratios_a + ratios_b))
    return rhythm


def phase_scan(
    seed: Tuple[int, int],
    steps: int,
    phi_ab: float,
    phi_berry: float,
    d_values: Iterable[int],
    s_spin: float = 0.5,
) -> dict:
    """Compute phase accumulation and Euler-Berry closure error.

    D is treated as an integer degree/defect/topological sector. The Euler
    phase contribution is modeled as Phi_E = 2*pi*s_spin*D. Closure error is
    epsilon = distance to nearest integer of total phase/(2*pi).
    """
    a, b = pair_orbit(seed, steps)
    rho = collatz_log_rhythm(a, b)
    # W_s is represented by the signed twin-prime imbalance in the Collatz pair.
    # This is not a canonical claim; it is a simulation choice.
    W = (np.array(b[:-1], dtype=float) - np.array(a[:-1], dtype=float)) / np.maximum(
        1.0, 0.5 * (np.array(a[:-1], dtype=float) + np.array(b[:-1], dtype=float))
    )
    phi_intention = np.cumsum(rho * KAPPA * W)
    final_phi_intention = float(phi_intention[-1])

    rows = []
    for D in d_values:
        phi_euler = 2.0 * math.pi * s_spin * D
        total = phi_ab + phi_berry + phi_euler + final_phi_intention
        phase_units = total / (2.0 * math.pi)
        epsilon = phase_units - round(phase_units)
        rows.append(
            {
                "D": int(D),
                "phi_euler": phi_euler,
                "total_phase": total,
                "phase_units": phase_units,
                "epsilon": epsilon,
                "abs_epsilon": abs(epsilon),
            }
        )

    return {
        "seed": seed,
        "steps": steps,
        "kappa_ln2_over_24pi": KAPPA,
        "phi_ab": phi_ab,
        "phi_berry": phi_berry,
        "final_phi_intention": final_phi_intention,
        "orbit_a": a,
        "orbit_b": b,
        "rho": rho.tolist(),
        "phi_intention_cumulative": phi_intention.tolist(),
        "D_scan": rows,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--p", type=int, default=11, help="first member of twin-prime seed")
    ap.add_argument("--steps", type=int, default=80)
    ap.add_argument("--phi-ab", type=float, default=0.73)
    ap.add_argument("--phi-berry", type=float, default=1.17)
    ap.add_argument("--d-min", type=int, default=-8)
    ap.add_argument("--d-max", type=int, default=8)
    ap.add_argument("--out", type=Path, default=Path("results/collatz_phase_results.json"))
    ap.add_argument("--figdir", type=Path, default=Path("figures"))
    args = ap.parse_args()

    seed = (args.p, args.p + 2)
    if not (is_prime(seed[0]) and is_prime(seed[1])):
        raise ValueError(f"Seed {seed} is not a twin-prime pair")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.figdir.mkdir(parents=True, exist_ok=True)

    data = phase_scan(
        seed=seed,
        steps=args.steps,
        phi_ab=args.phi_ab,
        phi_berry=args.phi_berry,
        d_values=range(args.d_min, args.d_max + 1),
    )
    args.out.write_text(json.dumps(data, indent=2), encoding="utf-8")

    x = np.arange(len(data["phi_intention_cumulative"]))
    plt.figure(figsize=(7, 4))
    plt.plot(x, data["phi_intention_cumulative"])
    plt.xlabel("Collatz step k")
    plt.ylabel("cumulative intention phase")
    plt.title(f"Intention phase from twin-prime seed {seed}")
    plt.tight_layout()
    plt.savefig(args.figdir / "collatz_intention_phase.png", dpi=180)
    plt.close()

    d = [r["D"] for r in data["D_scan"]]
    eps = [r["abs_epsilon"] for r in data["D_scan"]]
    plt.figure(figsize=(7, 4))
    plt.plot(d, eps, marker="o")
    plt.xlabel("Euler-Berry sector D")
    plt.ylabel("absolute closure error |epsilon|")
    plt.title("Euler-Berry phase closure scan")
    plt.tight_layout()
    plt.savefig(args.figdir / "euler_berry_epsilon_scan.png", dpi=180)
    plt.close()

    print(json.dumps({"out": str(args.out), "figdir": str(args.figdir), "best_D": min(data["D_scan"], key=lambda r: r["abs_epsilon"])}, indent=2))


if __name__ == "__main__":
    main()
